version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: demo-postgres
    restart: always
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  service:
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - postgres

