
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  hikari:
    maximum-pool-size: 200          # ? ?????????? ????????????? ????? ??????????
    minimum-idle: 50               # ??????? "??????" ??????????
    idle-timeout: 30000            # ????? ??????? ????????? idle ?????????? (??)
    max-lifetime: 1800000          # ???????????? ????? ????? ?????????? (??)
    connection-timeout: 60000      # ??????? ????? ????? ??????????? (??)
